[package]
name = "wake_me_when"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portable-atomic = "1.0.1"
parking_lot = "0.12.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }