disallowed-types = [
    { path = "core::sync::atomic::AtomicU64", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicI64", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicUsize", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicIsize", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicU32", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicI32", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicU16", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicI16", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicU8", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicI8", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicBool", reason = "use portable atomic instead" },
    { path = "core::sync::atomic::AtomicPtr", reason = "use portable atomic instead" },
]
